version: '3'
services:
  zipkin:
    image: openzipkin/zipkin
    ports:
      - 9411:9411
    networks:
      - microservices_network
  service-discovery-container:
    image: saraluciaaa/service-discovery-ecommerce-boot:1.0.0dev
    ports:
      - 8761:8761
    networks:
      - microservices_network
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_ZIPKIN_BASE-URL=http://zipkin:9411
      - SPRING_CONFIG_IMPORT=optional:configserver:http://cloud-config-container:9296/
  cloud-config-container:
    image: saraluciaaa/cloud-config-ecommerce-boot:1.0.0dev
    ports:
      - 9296:9296
    networks:
      - microservices_network
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_ZIPKIN_BASE-URL=http://zipkin:9411 
      - EUREKA_CLIENT_REGION=default 
      - EUREKA_CLIENT_AVAILABILITYZONES_DEFAULT=myzone 
      - EUREKA_CLIENT_SERVICEURL_MYZONE=http://service-discovery-container:8761/eureka 
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://service-discovery-container:8761/eureka/

networks: 
  microservices_network: 
    driver: bridge